[package]
name = "viewimg"
version = "0.17.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]
license = "MIT"
edition = "2021"
description = "OpenEXR and HDR image viewer"
homepage = "https://github.com/mandeep/viewimg"
repository = "https://github.com/mandeep/viewimg"
documentation = "https://github.com/mandeep/viewimg"
readme = "README.md"
exclude = ["tests/"]

[dependencies]
clap = { version = "=2.33.4", default-features = false }
image = { version = "=0.25.10", default-features = false, features = ["exr", "hdr", "png", "jpeg", "bmp", "gif", "ico", "tga", "tiff", "webp"] }
pixels = "=0.13.0"
winit = "=0.27.5"
winit_input_helper = "=0.13.0"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true
